Fix error at startup (#71)
Before this fix, when platform start with fresh db, we have an error :
2021-03-12 11:12:09,020 | ERROR | Failed start Organization Service org.exoplatform.services.organization.idm.PicketLinkIDMOrganizationServiceImpl, probably because of configuration error. Error occurs when initialize org.exoplatform.services.organization.OrganizationDatabaseInitializer [o.e.s.o.i.PicketLinkIDMOrganizationServiceImpl<Catalina-startStop-1>]
java.lang.RuntimeException: Failed start Organization Service org.exoplatform.services.organization.idm.PicketLinkIDMOrganizationServiceImpl, probably because of configuration error. Error occurs when initialize org.exoplatform.services.organization.OrganizationDatabaseInitializer
  at org.exoplatform.services.organization.BaseOrganizationService.start(BaseOrganizationService.java:91) ~[exo.core.component.organization.api-6.2.x-SNAPSHOT.jar:6.2.x-SNAPSHOT]

This commit rollback the impacted modification